In [12]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import pandas as pd
import numpy  as np

from sklearn.linear_model     import LogisticRegression
from sklearn.preprocessing   import StandardScaler
from sklearn.metrics         import confusion_matrix
from sklearn.metrics         import plot_confusion_matrix
from sklearn.metrics         import classification_report
from sklearn.metrics         import accuracy_score
from sklearn.metrics         import accuracy_score

In [13]:
df = pd.read_csv("C:/Users/ISD/Python_ali/fault_detection/Pv_Data2.csv")
df;
X = df.drop(['Target'],axis=1).values

Y=df.loc[:,'Target']
X.shape

(1600, 7)

In [14]:
inputs_train, inputs_test, targets_train, targets_test = train_test_split(X ,Y, test_size=0.3, random_state=0)

In [15]:
sc=StandardScaler()

scaler = sc.fit(inputs_train)
inputs_train = scaler.transform(inputs_train)
inputs_test = scaler.transform(inputs_test)

In [16]:
clf = LogisticRegression( solver='lbfgs', multi_class='auto',penalty='l2')

In [17]:
%%capture
clf.fit(inputs_train,targets_train)

In [18]:
ypred=clf.predict(inputs_test)
ypred;

In [19]:
ac=accuracy_score(targets_test,ypred)*100
ac

82.91666666666667

In [20]:
c=confusion_matrix(targets_test,ypred)
c

array([[37,  0,  0,  0,  1,  1,  0,  0,  0,  0],
       [ 0, 49,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 51,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 31,  0,  0,  0,  0,  3,  8],
       [ 3,  0,  0,  0, 37,  0,  0,  0,  3,  0],
       [ 3,  0,  0,  0,  1, 44,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0, 47,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 50,  0,  0],
       [46,  0,  0,  0,  7,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  2, 52]], dtype=int64)

In [21]:
ypred1=clf.predict(inputs_train)

In [22]:
ac1=accuracy_score(targets_train,ypred1)*100
ac1

84.73214285714286

In [23]:
c1=confusion_matrix(targets_train,ypred1)
c1

array([[108,   0,   0,   0,   9,   2,   0,   0,   2,   0],
       [  0, 111,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 109,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  97,   4,   1,   0,   0,   7,   9],
       [ 12,   0,   0,   0,  97,   3,   0,   0,   5,   0],
       [  5,   0,   0,   0,   3, 100,   0,   0,   2,   0],
       [  0,   0,   0,   0,   0,   0, 113,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 110,   0,   0],
       [ 81,   0,   0,   0,  15,   7,   0,   0,   3,   0],
       [  0,   0,   0,   0,   0,   2,   0,   0,   2, 101]], dtype=int64)

In [24]:
YR=np.concatenate((targets_test,targets_train),axis=0)

In [25]:
YP = np.concatenate((ypred,ypred1), axis=0)


In [26]:
ac2=accuracy_score(YR,YP)*100
ac2

84.1875

In [115]:
c2=confusion_matrix(YR,YP)
c2

array([[116,   0,   0,   7,  15,   0,  11,   0,  11,   0],
       [  0, 111,   0,  49,   0,   0,   0,   0,   0,   0],
       [  0,   0, 159,   0,   0,   0,   0,   1,   0,   0],
       [  0,  22,   0,  98,   0,  40,   0,   0,   0,   0],
       [ 22,   0,   0,  13,  42,  15,  20,   0,  48,   0],
       [  0,  11,   0,  30,   0,  53,  60,   0,   0,   6],
       [ 16,   0,   0,  14,  44,  11,  25,   0,  50,   0],
       [  0,   0,   0,   0,   0,   0,   0, 160,   0,   0],
       [ 77,   0,   0,  10,  35,   0,  15,   0,  23,   0],
       [  0,  25,   0,   0,   0,   0,   0,   0,   0, 135]], dtype=int64)