In [19]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import pandas as pd
import numpy as np

from sklearn.linear_model    import LogisticRegression
from sklearn.preprocessing   import StandardScaler
from sklearn.metrics         import confusion_matrix
from sklearn.metrics         import plot_confusion_matrix
from sklearn.metrics         import classification_report
from sklearn.metrics         import accuracy_score
from sklearn.metrics         import accuracy_score

In [20]:
df = pd.read_csv("C:/Users/ISD/Python_ali/fault_detection/Pv_Data2.csv")
df;
X = df.drop(['Target'],axis=1).values

Y=df.loc[:,'Target']
X.shape

(1600, 7)

In [21]:
pca = PCA(n_components=7)

In [22]:
pca.fit(X)

PCA(n_components=7)

In [23]:
X_pca = pca.transform(X)

In [24]:
inputs_train, inputs_test, targets_train, targets_test = train_test_split(X_pca ,Y, test_size=0.3, random_state=0)

In [25]:
sc=StandardScaler()

scaler = sc.fit(inputs_train)
inputs_train = scaler.transform(inputs_train)
inputs_test = scaler.transform(inputs_test)

In [26]:
clf = LogisticRegression( solver='lbfgs', multi_class='multinomial',penalty='l2')

In [27]:
%%capture
clf.fit(inputs_train,targets_train)

In [28]:
ypred=clf.predict(inputs_test)
ypred;

In [29]:
ac=accuracy_score(targets_test,ypred)*100
ac

95.20833333333333

In [30]:
c=confusion_matrix(targets_test,ypred)
c

array([[37,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0, 48,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0, 48,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0, 42,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  3,  0],
       [ 1,  1,  0,  0,  1, 44,  0,  1,  2,  0],
       [ 0,  1,  0,  0,  2,  0, 44,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0, 49,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0, 50,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 55]], dtype=int64)

In [31]:
ypred1=clf.predict(inputs_train)

In [32]:
ac1=accuracy_score(targets_train,ypred1)*100
ac1

94.375

In [33]:
c1=confusion_matrix(targets_train,ypred1)
c1

array([[112,   0,   0,   0,   1,   0,   2,   0,   6,   0],
       [  0, 108,   0,   0,   1,   0,   2,   0,   0,   0],
       [  0,   0, 108,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0,   0, 115,   0,   2,   0,   0,   0,   1],
       [  1,   0,   0,   0, 108,   0,   0,   0,   8,   0],
       [  0,   0,   0,   0,   4, 103,   0,   0,   3,   0],
       [  0,   5,   0,   0,   2,   0, 103,   0,   3,   0],
       [  0,   0,   3,   0,   0,   1,   0, 106,   0,   0],
       [  6,   0,   0,   0,   8,   2,   0,   0,  90,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0,   0, 104]], dtype=int64)

In [34]:
YR=np.concatenate((targets_test,targets_train),axis=0)

In [35]:
YP = np.concatenate((ypred,ypred1), axis=0)

In [36]:
ac2=accuracy_score(YR,YP)*100
ac2

94.625

In [119]:
c2=confusion_matrix(YR,YP)
c2

array([[133,   0,   0,   1,   2,   0,   0,   0,  22,   2],
       [  0,  22,  88,   0,   0,   0,  26,  24,   0,   0],
       [  0,   0, 160,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 118,   0,   0,   0,   0,   0,  42],
       [124,   0,   0,   0,  12,   0,   0,   0,  19,   5],
       [ 19,   2,   2,  19,  64,   9,   0,   0,  30,  15],
       [140,   0,   0,   0,   0,   0,   0,   0,  15,   5],
       [  0,   0, 160,   0,   0,   0,   0,   0,   0,   0],
       [130,   0,   0,   0,   0,   0,   0,   0,  26,   4],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 160]], dtype=int64)